import Navbar from "@/components/Shared/Navbar";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata = {
  title: "My Test App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${poppins.className}, max-w-7xl mx-auto px-4 md:px-8 overflow-x-hidden border-2 border-red-500`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
